### ISSUE TITLE
LoRaWAN with NodeJS - why?

### ISSUE THREAD

**Issue by chainhead** [kartben/lorawan-node-simulator#2]
First off, *congratulations* on building this!! I am sure, many will benefit with this simulator.

Quick question: Did you choose NodeJS because of its event loop and asynchronous programming paradigm? I am curious to know, if the simulator would have benefit with a programming language that did _not_ offer an event loop or asynchronous programming.

**Comment by kartben** [comment]
Hey, thanks for the kind words!

Regarding NodeJS/TypeScript, there was initially no other reason than being able to piggyback some existing libraries for [packet encoding/decoding](https://github.com/anthonykirby/lora-packet) as well as a [packet forwarder](https://github.com/antoniobusrod/packet-forwarder) that saved me quite some time. 

Now, that being said, I found the programming model to be well-aligned with the concepts of a network simulation (e.g simulated devices "emit" fake packets/events), and while I'm sure other programming languages would have allowed to achieve similar results, it may have resulted in a bit more boilerplate code.

**Comment by kartben** [comment]
I'll be closing this for now.  Let me know if you have other questions!
